framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {  }

        failure_transport: failed

        transports:
            amqp_user:
                dsn: '%env(string:MESSENGER_TRANSPORT_DSN)%'
                serializer: ~
                retry_strategy:
                    max_retries: 1
                    delay: 1000
                    multiplier: 1
                options:
                    vhost: '%env(string:MESSENGER_VHOST)%'
                    exhange:
                        name:  '%env(string:MESSENGER_EXCHANGE)%'
                        type: direct
                    queues:
                        user_queue:
                            binding_keys: [user_queue]
                    autosetup: true
            failed:
                dsn: 'doctrine://default?queue_name=failed'

        routing:
            'App\Messenger\Message\UserRegisterMessage': amqp_user
